#!/usr/bin/env python3
"""Embed FasTris' three built-in music assets as generated C++ byte arrays."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping

SLOTS = ("menu", "gameplay", "intense")
EXTENSIONS = ("ogg", "mp3", "wav")


def discover_slot(source_dir: Path, slot: str) -> Path:
    matches = [source_dir / f"{slot}.{ext}" for ext in EXTENSIONS if (source_dir / f"{slot}.{ext}").is_file()]
    if len(matches) != 1:
        names = ", ".join(f"{slot}.{ext}" for ext in EXTENSIONS)
        raise ValueError(f"music slot '{slot}' requires exactly one of: {names}; found {len(matches)}")
    return matches[0]


def format_name(path: Path) -> str:
    ext = path.suffix.lower()
    mapping = {".ogg": "Ogg", ".mp3": "Mp3", ".wav": "Wav"}
    if ext not in mapping:
        raise ValueError(f"unsupported music format: {path.suffix}")
    return mapping[ext]


def _array_name(slot: str) -> str:
    return "k" + slot.capitalize() + "Music"


def _format_bytes(data: bytes) -> str:
    if not data:
        return "    0x00"
    rows: list[str] = []
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk))
    return ",\n".join(rows)


def emit_cpp(output: Path, assets: Mapping[str, Path]) -> None:
    missing = [slot for slot in SLOTS if slot not in assets]
    if missing:
        raise ValueError("missing music slots: " + ", ".join(missing))
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/embed_music.py. Do not edit.",
        '#include "music_assets.hpp"',
        "#include <cstdint>",
        "",
        "namespace fasttris::app {",
        "namespace {",
    ]
    for slot in SLOTS:
        data = assets[slot].read_bytes()
        lines.extend([
            f"static constexpr std::uint8_t {_array_name(slot)}[] = {{",
            _format_bytes(data),
            "};",
        ])
    lines.extend(["} // namespace", "", "EmbeddedMusicAsset embeddedMusicAsset(MusicTrack track) {", "    switch (track) {"])
    enum_names = {"menu": "Menu", "gameplay": "Gameplay", "intense": "Intense"}
    for slot in SLOTS:
        fmt = format_name(assets[slot])
        arr = _array_name(slot)
        lines.append(f"        case MusicTrack::{enum_names[slot]}: return {{{arr}, sizeof({arr}), MusicFormat::{fmt}}};")
    lines.extend([
        "        default: return {};",
        "    }",
        "}",
        "} // namespace fasttris::app",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        assets = {slot: discover_slot(args.source_dir, slot) for slot in SLOTS}
        emit_cpp(args.output, assets)
    except (OSError, ValueError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
